echo starting!
python .\pyrtcm_test.py -n AGTIC
python .\pyrtcm_test.py -n ARAGO
python .\pyrtcm_test.py -n DUVAL
python .\pyrtcm_test.py -n PGUI45
python .\pyrtcm_test.py -n DELMO
python .\pyrtcm_test.py -n EVOM
python .\pyrtcm_test.py -n WL36
python .\pyrtcm_test.py -n OUIL
python .\pyrtcm_test.py -n JGUI
python .\pyrtcm_test.py -n PIERRO
python .\pyrtcm_test.py -n VIGN
python .\pyrtcm_test.py -n ENSIP
python .\pyrtcm_test.py -n GPTR
python .\pyrtcm_test.py -n KUFF
python .\pyrtcm_test.py -n HTEG
python .\pyrtcm_test.py -n PM52
python .\pyrtcm_test.py -n MONTI
python .\pyrtcm_test.py -n TUCH
python .\pyrtcm_test.py -n LHUI
python .\pyrtcm_test.py -n SSB
python .\pyrtcm_test.py -n CLMRY
python .\pyrtcm_test.py -n ALEX
python .\pyrtcm_test.py -n AUBU
python .\pyrtcm_test.py -n PARD
python .\pyrtcm_test.py -n MTP2
python .\pyrtcm_test.py -n NICE
python .\pyrtcm_test.py -n LNE1
python .\pyrtcm_test.py -n STMR
python .\pyrtcm_test.py -n WLBH
python .\pyrtcm_test.py -n SOPH
python .\pyrtcm_test.py -n ERCK
python .\pyrtcm_test.py -n CITRU
python .\pyrtcm_test.py -n DECAL
python .\pyrtcm_test.py -n ASTA
python .\pyrtcm_test.py -n HEYT
python .\pyrtcm_test.py -n POL25
python .\pyrtcm_test.py -n TOPH
python .\pyrtcm_test.py -n PRISM
python .\pyrtcm_test.py -n FRTK52
python .\pyrtcm_test.py -n BABA
python .\pyrtcm_test.py -n FRTKB1
python .\pyrtcm_test.py -n FLG49
python .\pyrtcm_test.py -n DAMA
python .\pyrtcm_test.py -n SKYF
python .\pyrtcm_test.py -n SABI
python .\pyrtcm_test.py -n BEROY
python .\pyrtcm_test.py -n CTA1
python .\pyrtcm_test.py -n ETAA
python .\pyrtcm_test.py -n PYLA
python .\pyrtcm_test.py -n GVIL
python .\pyrtcm_test.py -n LESTR
python .\pyrtcm_test.py -n BAYS1
python .\pyrtcm_test.py -n REM57
python .\pyrtcm_test.py -n MELCAS
python .\pyrtcm_test.py -n SAUDU
python .\pyrtcm_test.py -n PJ51
python .\pyrtcm_test.py -n RB81
python .\pyrtcm_test.py -n DESVR
python .\pyrtcm_test.py -n BIGO1
python .\pyrtcm_test.py -n FIGUE
python .\pyrtcm_test.py -n FRTK31
python .\pyrtcm_test.py -n VLG89
python .\pyrtcm_test.py -n EVCC
python .\pyrtcm_test.py -n BDN
python .\pyrtcm_test.py -n SOISS
python .\pyrtcm_test.py -n LACB
python .\pyrtcm_test.py -n RTK09
python .\pyrtcm_test.py -n EOAA
python .\pyrtcm_test.py -n CHAUMES
python .\pyrtcm_test.py -n LAPO
python .\pyrtcm_test.py -n KAL1
python .\pyrtcm_test.py -n FE08
python .\pyrtcm_test.py -n CIRO
python .\pyrtcm_test.py -n TISNE
python .\pyrtcm_test.py -n BSN1
python .\pyrtcm_test.py -n CAVZN
python .\pyrtcm_test.py -n GEDA
python .\pyrtcm_test.py -n FTCH
python .\pyrtcm_test.py -n DujDub
python .\pyrtcm_test.py -n VALDM
python .\pyrtcm_test.py -n DEBEN
python .\pyrtcm_test.py -n TALB
python .\pyrtcm_test.py -n CETTE
python .\pyrtcm_test.py -n MAUP
python .\pyrtcm_test.py -n HAUJ
python .\pyrtcm_test.py -n PA71
python .\pyrtcm_test.py -n PAKI
python .\pyrtcm_test.py -n ALZ22
python .\pyrtcm_test.py -n T002
python .\pyrtcm_test.py -n LCBC
python .\pyrtcm_test.py -n SROG
python .\pyrtcm_test.py -n LAF32
python .\pyrtcm_test.py -n EIDS
python .\pyrtcm_test.py -n MPZT
python .\pyrtcm_test.py -n CRK
python .\pyrtcm_test.py -n SLINS
python .\pyrtcm_test.py -n NATI
python .\pyrtcm_test.py -n STAVE
python .\pyrtcm_test.py -n AGSA
python .\pyrtcm_test.py -n LEMA
python .\pyrtcm_test.py -n YOYO
python .\pyrtcm_test.py -n DELTA
python .\pyrtcm_test.py -n OLIM
python .\pyrtcm_test.py -n KORPELA2
python .\pyrtcm_test.py -n BSLL
python .\pyrtcm_test.py -n ADAM
python .\pyrtcm_test.py -n ILLE
python .\pyrtcm_test.py -n NORA
python .\pyrtcm_test.py -n LR980
python .\pyrtcm_test.py -n CAR
python .\pyrtcm_test.py -n ARRAS
python .\pyrtcm_test.py -n RJBA
python .\pyrtcm_test.py -n GDCP
python .\pyrtcm_test.py -n JAVER
python .\pyrtcm_test.py -n SHLT87
python .\pyrtcm_test.py -n CDFX
python .\pyrtcm_test.py -n AGF1
python .\pyrtcm_test.py -n BANN
python .\pyrtcm_test.py -n CODAR
python .\pyrtcm_test.py -n DRUM
python .\pyrtcm_test.py -n JOCO
python .\pyrtcm_test.py -n LEND
python .\pyrtcm_test.py -n MEHE
python .\pyrtcm_test.py -n SYSD
python .\pyrtcm_test.py -n OMT1
python .\pyrtcm_test.py -n AURI
python .\pyrtcm_test.py -n URS1
python .\pyrtcm_test.py -n AGSB
python .\pyrtcm_test.py -n SEAS
python .\pyrtcm_test.py -n ENK1
python .\pyrtcm_test.py -n BIO
python .\pyrtcm_test.py -n LIENSS
python .\pyrtcm_test.py -n DIA1
python .\pyrtcm_test.py -n UEAU
python .\pyrtcm_test.py -n ENSMM
python .\pyrtcm_test.py -n GERS
python .\pyrtcm_test.py -n RAV35
python .\pyrtcm_test.py -n IUTC
python .\pyrtcm_test.py -n MANTA
python .\pyrtcm_test.py -n LXLY
python .\pyrtcm_test.py -n ASD21
python .\pyrtcm_test.py -n LUNE
python .\pyrtcm_test.py -n CLFA
python .\pyrtcm_test.py -n CVRA
python .\pyrtcm_test.py -n BTCHZ
python .\pyrtcm_test.py -n CHSL
python .\pyrtcm_test.py -n NELER
python .\pyrtcm_test.py -n PHAC
python .\pyrtcm_test.py -n CDA2
python .\pyrtcm_test.py -n PRDR
python .\pyrtcm_test.py -n SIGEO
python .\pyrtcm_test.py -n GOHAN
python .\pyrtcm_test.py -n PNRB
python .\pyrtcm_test.py -n GEOREVA
python .\pyrtcm_test.py -n 56MOUS
python .\pyrtcm_test.py -n LEC76
python .\pyrtcm_test.py -n LPA16
python .\pyrtcm_test.py -n UEAT
python .\pyrtcm_test.py -n IUTA
python .\pyrtcm_test.py -n GREZ77
python .\pyrtcm_test.py -n OFFNE
python .\pyrtcm_test.py -n BDUN
python .\pyrtcm_test.py -n FLAV
python .\pyrtcm_test.py -n BOBBY
python .\pyrtcm_test.py -n GERM
python .\pyrtcm_test.py -n ENSIL
python .\pyrtcm_test.py -n ENSG
python .\pyrtcm_test.py -n MLLT
python .\pyrtcm_test.py -n JODO
python .\pyrtcm_test.py -n VILBO
python .\pyrtcm_test.py -n EL14
python .\pyrtcm_test.py -n WP45
python .\pyrtcm_test.py -n CDA1
python .\pyrtcm_test.py -n DOMV
python .\pyrtcm_test.py -n BEDEDE
python .\pyrtcm_test.py -n ABD1
python .\pyrtcm_test.py -n PALLU
python .\pyrtcm_test.py -n CERM
python .\pyrtcm_test.py -n HSG68
python .\pyrtcm_test.py -n JMU-ROBOTICS
python .\pyrtcm_test.py -n AP36
python .\pyrtcm_test.py -n YUUKI
python .\pyrtcm_test.py -n GM21
python .\pyrtcm_test.py -n CS49
python .\pyrtcm_test.py -n WIGNE
python .\pyrtcm_test.py -n CLBM
python .\pyrtcm_test.py -n MACQU
python .\pyrtcm_test.py -n RPJMN
python .\pyrtcm_test.py -n KIRR
python .\pyrtcm_test.py -n PROS
python .\pyrtcm_test.py -n CRA1
python .\pyrtcm_test.py -n NORT
python .\pyrtcm_test.py -n LGNT
python .\pyrtcm_test.py -n CAZ0
python .\pyrtcm_test.py -n GUIGO
python .\pyrtcm_test.py -n TBVU
python .\pyrtcm_test.py -n ULCO1
python .\pyrtcm_test.py -n VALVH
python .\pyrtcm_test.py -n VICQ
python .\pyrtcm_test.py -n REMKA
python .\pyrtcm_test.py -n ABBEV
python .\pyrtcm_test.py -n KOULM
python .\pyrtcm_test.py -n KAL2
python .\pyrtcm_test.py -n LEN1
python .\pyrtcm_test.py -n TDPT
python .\pyrtcm_test.py -n CORA
python .\pyrtcm_test.py -n SEDB
python .\pyrtcm_test.py -n JMN72
python .\pyrtcm_test.py -n THAIS
python .\pyrtcm_test.py -n BETH
python .\pyrtcm_test.py -n SART
python .\pyrtcm_test.py -n HONO
python .\pyrtcm_test.py -n DMZ
python .\pyrtcm_test.py -n GDCRT
python .\pyrtcm_test.py -n BCBA
python .\pyrtcm_test.py -n CAMB
python .\pyrtcm_test.py -n MANT
python .\pyrtcm_test.py -n ESTMO
python .\pyrtcm_test.py -n SOY25
python .\pyrtcm_test.py -n DID37
python .\pyrtcm_test.py -n LAON
python .\pyrtcm_test.py -n NOUE
python .\pyrtcm_test.py -n CAVX
python .\pyrtcm_test.py -n BRTAT
python .\pyrtcm_test.py -n FLO18
python .\pyrtcm_test.py -n SN22
python .\pyrtcm_test.py -n CHAMB
python .\pyrtcm_test.py -n VANDE
python .\pyrtcm_test.py -n SBOIS
python .\pyrtcm_test.py -n ALTD
python .\pyrtcm_test.py -n RTK23
python .\pyrtcm_test.py -n STCRE
python .\pyrtcm_test.py -n mara
python .\pyrtcm_test.py -n GIR1
python .\pyrtcm_test.py -n ANDR
python .\pyrtcm_test.py -n LFRG
python .\pyrtcm_test.py -n GCPV
python .\pyrtcm_test.py -n BD60
python .\pyrtcm_test.py -n COLL
python .\pyrtcm_test.py -n CLEM
python .\pyrtcm_test.py -n ARN0
python .\pyrtcm_test.py -n BARR
python .\pyrtcm_test.py -n CPN26
python .\pyrtcm_test.py -n STLYS
python .\pyrtcm_test.py -n GAECJ
python .\pyrtcm_test.py -n BEAU45
python .\pyrtcm_test.py -n ALC22
python .\pyrtcm_test.py -n JD45
python .\pyrtcm_test.py -n HYE1
python .\pyrtcm_test.py -n CAYE
python .\pyrtcm_test.py -n GARRI
python .\pyrtcm_test.py -n SERO
python .\pyrtcm_test.py -n AA41
python .\pyrtcm_test.py -n SAM0
python .\pyrtcm_test.py -n PA17
python .\pyrtcm_test.py -n ACAC
python .\pyrtcm_test.py -n SGDF1
python .\pyrtcm_test.py -n MET
python .\pyrtcm_test.py -n SPB28
python .\pyrtcm_test.py -n LTC2
python .\pyrtcm_test.py -n LAX
python .\pyrtcm_test.py -n BIVL1
python .\pyrtcm_test.py -n LIGR
python .\pyrtcm_test.py -n SBEC
python .\pyrtcm_test.py -n TOUCH
python .\pyrtcm_test.py -n TOUR
python .\pyrtcm_test.py -n CRTK
python .\pyrtcm_test.py -n OLIMI
python .\pyrtcm_test.py -n KGL29
python .\pyrtcm_test.py -n FRSAM
python .\pyrtcm_test.py -n PNRLF
python .\pyrtcm_test.py -n SAM1
python .\pyrtcm_test.py -n LFRGL
python .\pyrtcm_test.py -n HOFF
python .\pyrtcm_test.py -n KD29
python .\pyrtcm_test.py -n CHAU
python .\pyrtcm_test.py -n IUEM
python .\pyrtcm_test.py -n CH27
python .\pyrtcm_test.py -n LAWI
python .\pyrtcm_test.py -n TUTUT
python .\pyrtcm_test.py -n MGSL
python .\pyrtcm_test.py -n TOM16
python .\pyrtcm_test.py -n ANTO
python .\pyrtcm_test.py -n URC90
python .\pyrtcm_test.py -n AIDE
python .\pyrtcm_test.py -n WINTZ
python .\pyrtcm_test.py -n BILL
python .\pyrtcm_test.py -n LAVKO
python .\pyrtcm_test.py -n HAUR
python .\pyrtcm_test.py -n MAND
python .\pyrtcm_test.py -n RAYN
python .\pyrtcm_test.py -n BARGE
python .\pyrtcm_test.py -n HAME
python .\pyrtcm_test.py -n GROF
python .\pyrtcm_test.py -n OMB
python .\pyrtcm_test.py -n JFD3
python .\pyrtcm_test.py -n PHIND
python .\pyrtcm_test.py -n SARS
python .\pyrtcm_test.py -n TG89
python .\pyrtcm_test.py -n PERA
python .\pyrtcm_test.py -n SDMG
python .\pyrtcm_test.py -n FRAE
python .\pyrtcm_test.py -n DEWB
python .\pyrtcm_test.py -n EMC2
python .\pyrtcm_test.py -n LEGTA
python .\pyrtcm_test.py -n BLGC
python .\pyrtcm_test.py -n DEPO
python .\pyrtcm_test.py -n TRALY
python .\pyrtcm_test.py -n VAGC
python .\pyrtcm_test.py -n BMDC
python .\pyrtcm_test.py -n EJPB
python .\pyrtcm_test.py -n LHER
python .\pyrtcm_test.py -n GEOP
python .\pyrtcm_test.py -n ASAGI
python .\pyrtcm_test.py -n CD49
python .\pyrtcm_test.py -n THUM
python .\pyrtcm_test.py -n SC89
python .\pyrtcm_test.py -n LLS1
python .\pyrtcm_test.py -n STRA
python .\pyrtcm_test.py -n CEAU2
python .\pyrtcm_test.py -n PUNK
python .\pyrtcm_test.py -n FORCA
python .\pyrtcm_test.py -n DEFLAU
python .\pyrtcm_test.py -n LDOC
python .\pyrtcm_test.py -n PEPE
python .\pyrtcm_test.py -n MIL70
python .\pyrtcm_test.py -n COTT
python .\pyrtcm_test.py -n SOUQ
python .\pyrtcm_test.py -n TOMB
python .\pyrtcm_test.py -n AN79
python .\pyrtcm_test.py -n LELEU
python .\pyrtcm_test.py -n EPI21
python .\pyrtcm_test.py -n BZH35
python .\pyrtcm_test.py -n STPOL
python .\pyrtcm_test.py -n CA53
python .\pyrtcm_test.py -n PSHS
python .\pyrtcm_test.py -n CIAS
python .\pyrtcm_test.py -n ASHW
python .\pyrtcm_test.py -n SEL12
python .\pyrtcm_test.py -n CBER
python .\pyrtcm_test.py -n MGC1
python .\pyrtcm_test.py -n M2O
python .\pyrtcm_test.py -n BURA
python .\pyrtcm_test.py -n ISIA
python .\pyrtcm_test.py -n NACX
python .\pyrtcm_test.py -n LBFLT
python .\pyrtcm_test.py -n LRSEC
python .\pyrtcm_test.py -n AGFM
python .\pyrtcm_test.py -n DanbyWiske
python .\pyrtcm_test.py -n BEN50
python .\pyrtcm_test.py -n BIST
python .\pyrtcm_test.py -n LOUL
python .\pyrtcm_test.py -n BALL
python .\pyrtcm_test.py -n ZIJP
python .\pyrtcm_test.py -n PARC
python .\pyrtcm_test.py -n DRGHZ
python .\pyrtcm_test.py -n JUDI
python .\pyrtcm_test.py -n TOR35
python .\pyrtcm_test.py -n SCV1
python .\pyrtcm_test.py -n ZSZ1
python .\pyrtcm_test.py -n MAGN
python .\pyrtcm_test.py -n LM65
python .\pyrtcm_test.py -n PORH
python .\pyrtcm_test.py -n TD04
python .\pyrtcm_test.py -n PHIL
python .\pyrtcm_test.py -n NLDA
python .\pyrtcm_test.py -n GUID
python .\pyrtcm_test.py -n AEJB
python .\pyrtcm_test.py -n COIC
python .\pyrtcm_test.py -n T001
python .\pyrtcm_test.py -n RC02
python .\pyrtcm_test.py -n CRUS
python .\pyrtcm_test.py -n VIN26
python .\pyrtcm_test.py -n ROMS1
python .\pyrtcm_test.py -n NINO
python .\pyrtcm_test.py -n ATCC
python .\pyrtcm_test.py -n NODE
python .\pyrtcm_test.py -n MELA
python .\pyrtcm_test.py -n JUAN
python .\pyrtcm_test.py -n CRNF
python .\pyrtcm_test.py -n GERG
python .\pyrtcm_test.py -n BAYFIELD
python .\pyrtcm_test.py -n GY45
python .\pyrtcm_test.py -n SVB7
python .\pyrtcm_test.py -n TH23
python .\pyrtcm_test.py -n COND
python .\pyrtcm_test.py -n POUZ
python .\pyrtcm_test.py -n NAERA2372
python .\pyrtcm_test.py -n LCJM
python .\pyrtcm_test.py -n ELA5
python .\pyrtcm_test.py -n OGIER
python .\pyrtcm_test.py -n GWMD
python .\pyrtcm_test.py -n JNOS
python .\pyrtcm_test.py -n DYVA
python .\pyrtcm_test.py -n AMRT
python .\pyrtcm_test.py -n ROCiochinaIL
python .\pyrtcm_test.py -n UPP
python .\pyrtcm_test.py -n KEILLORFARM
python .\pyrtcm_test.py -n KOT71
python .\pyrtcm_test.py -n 1234
python .\pyrtcm_test.py -n GORA
python .\pyrtcm_test.py -n TPGN
python .\pyrtcm_test.py -n CSDL
python .\pyrtcm_test.py -n KEME
python .\pyrtcm_test.py -n WHIT
python .\pyrtcm_test.py -n MLLC
python .\pyrtcm_test.py -n KERKE
python .\pyrtcm_test.py -n Tuulenkuja
python .\pyrtcm_test.py -n UEAB
python .\pyrtcm_test.py -n SGB1
python .\pyrtcm_test.py -n GRIG
python .\pyrtcm_test.py -n MTLDR
python .\pyrtcm_test.py -n MEDW
python .\pyrtcm_test.py -n FELB
python .\pyrtcm_test.py -n UELI
python .\pyrtcm_test.py -n HNVA
python .\pyrtcm_test.py -n HORA
python .\pyrtcm_test.py -n FD41
python .\pyrtcm_test.py -n MACO
python .\pyrtcm_test.py -n KOUD
python .\pyrtcm_test.py -n GRENAY
python .\pyrtcm_test.py -n AJA1
python .\pyrtcm_test.py -n 56MO
python .\pyrtcm_test.py -n FOON
python .\pyrtcm_test.py -n FM70
python .\pyrtcm_test.py -n GRPE
python .\pyrtcm_test.py -n BORD
python .\pyrtcm_test.py -n CARC
python .\pyrtcm_test.py -n LINON
python .\pyrtcm_test.py -n NINA
python .\pyrtcm_test.py -n GURAN
python .\pyrtcm_test.py -n SRTK
python .\pyrtcm_test.py -n EFIX
python .\pyrtcm_test.py -n MRLX
python .\pyrtcm_test.py -n 8412
python .\pyrtcm_test.py -n JURE
python .\pyrtcm_test.py -n PAS64
python .\pyrtcm_test.py -n WITT
python .\pyrtcm_test.py -n PARYG
python .\pyrtcm_test.py -n chcnavfin
python .\pyrtcm_test.py -n BTD1
python .\pyrtcm_test.py -n PNPAI
python .\pyrtcm_test.py -n CLAUD
python .\pyrtcm_test.py -n VDH72
python .\pyrtcm_test.py -n CCPI
python .\pyrtcm_test.py -n UCBL
python .\pyrtcm_test.py -n huovila
python .\pyrtcm_test.py -n BATIV
python .\pyrtcm_test.py -n AVUL
python .\pyrtcm_test.py -n BARB
python .\pyrtcm_test.py -n ENSG2
python .\pyrtcm_test.py -n VDM51
python .\pyrtcm_test.py -n ROAIX
python .\pyrtcm_test.py -n CALIG
python .\pyrtcm_test.py -n CARA
python .\pyrtcm_test.py -n CABA
python .\pyrtcm_test.py -n ECOR
python .\pyrtcm_test.py -n FDN1
python .\pyrtcm_test.py -n MIRMENHOF
python .\pyrtcm_test.py -n LULE
python .\pyrtcm_test.py -n ALEN
python .\pyrtcm_test.py -n FAYO
python .\pyrtcm_test.py -n FOUR1
python .\pyrtcm_test.py -n GILOC
python .\pyrtcm_test.py -n MSE2
python .\pyrtcm_test.py -n BDFD
python .\pyrtcm_test.py -n VIN65
python .\pyrtcm_test.py -n SABO
python .\pyrtcm_test.py -n BK18
python .\pyrtcm_test.py -n PARG
python .\pyrtcm_test.py -n ELV1
python .\pyrtcm_test.py -n ARKG
python .\pyrtcm_test.py -n CAEN14
python .\pyrtcm_test.py -n HAFL
python .\pyrtcm_test.py -n PDA1
python .\pyrtcm_test.py -n CT
python .\pyrtcm_test.py -n LAVZ
python .\pyrtcm_test.py -n FP14
python .\pyrtcm_test.py -n RC03
python .\pyrtcm_test.py -n MVITRY
python .\pyrtcm_test.py -n LPDLL
python .\pyrtcm_test.py -n PIER
python .\pyrtcm_test.py -n AMLS
python .\pyrtcm_test.py -n MDA21
python .\pyrtcm_test.py -n BESE
python .\pyrtcm_test.py -n DREUXS
python .\pyrtcm_test.py -n ETPA
python .\pyrtcm_test.py -n GMCP
python .\pyrtcm_test.py -n LAC5
python .\pyrtcm_test.py -n LRB1
python .\pyrtcm_test.py -n AE1
python .\pyrtcm_test.py -n BZH29
python .\pyrtcm_test.py -n BNFL
python .\pyrtcm_test.py -n STJEA
python .\pyrtcm_test.py -n BLAR
python .\pyrtcm_test.py -n FASPE
python .\pyrtcm_test.py -n RUF01
python .\pyrtcm_test.py -n FSS02
python .\pyrtcm_test.py -n SGHF
python .\pyrtcm_test.py -n MURI
python .\pyrtcm_test.py -n POSD
python .\pyrtcm_test.py -n SSAP
python .\pyrtcm_test.py -n PELY
python .\pyrtcm_test.py -n ROLF2
python .\pyrtcm_test.py -n KDCS
python .\pyrtcm_test.py -n MARC
python .\pyrtcm_test.py -n VTEJ
python .\pyrtcm_test.py -n ROLF
python .\pyrtcm_test.py -n EMIL
python .\pyrtcm_test.py -n BRTK
python .\pyrtcm_test.py -n BXATI
python .\pyrtcm_test.py -n GYSZ
python .\pyrtcm_test.py -n MFRT8
python .\pyrtcm_test.py -n CS01
python .\pyrtcm_test.py -n PGSL
python .\pyrtcm_test.py -n VIKK
python .\pyrtcm_test.py -n SARI
python .\pyrtcm_test.py -n CSAT
python .\pyrtcm_test.py -n MEZO
python .\pyrtcm_test.py -n VMND
python .\pyrtcm_test.py -n HRZL
python .\pyrtcm_test.py -n MONO
python .\pyrtcm_test.py -n DERE
python .\pyrtcm_test.py -n BES1
python .\pyrtcm_test.py -n RAJT2
python .\pyrtcm_test.py -n ABON
python .\pyrtcm_test.py -n SBG1
python .\pyrtcm_test.py -n BLGH
python .\pyrtcm_test.py -n JFSZ
python .\pyrtcm_test.py -n SOTI
python .\pyrtcm_test.py -n VECS
python .\pyrtcm_test.py -n KOLR
python .\pyrtcm_test.py -n PIXI
python .\pyrtcm_test.py -n HOLO
python .\pyrtcm_test.py -n FICS
python .\pyrtcm_test.py -n TOTM
python .\pyrtcm_test.py -n MOSZ
python .\pyrtcm_test.py -n SBBP
python .\pyrtcm_test.py -n KUTI
python .\pyrtcm_test.py -n ZBIO
python .\pyrtcm_test.py -n SZLA
python .\pyrtcm_test.py -n ZPAT
python .\pyrtcm_test.py -n PRJZS
python .\pyrtcm_test.py -n GREG
python .\pyrtcm_test.py -n KAR1
python .\pyrtcm_test.py -n TUGY
python .\pyrtcm_test.py -n KOPE
python .\pyrtcm_test.py -n NADU
python .\pyrtcm_test.py -n KEND
python .\pyrtcm_test.py -n DOBO
python .\pyrtcm_test.py -n KVSD
python .\pyrtcm_test.py -n DUDA
python .\pyrtcm_test.py -n HMIL
python .\pyrtcm_test.py -n RABA
python .\pyrtcm_test.py -n SOVANY
python .\pyrtcm_test.py -n SLHI
python .\pyrtcm_test.py -n BFK1
python .\pyrtcm_test.py -n SMVR
python .\pyrtcm_test.py -n LACA
python .\pyrtcm_test.py -n MET1
python .\pyrtcm_test.py -n ELES
python .\pyrtcm_test.py -n NAGY
python .\pyrtcm_test.py -n ZDRI
python .\pyrtcm_test.py -n SAMJ
python .\pyrtcm_test.py -n KAPU
python .\pyrtcm_test.py -n KAMA
python .\pyrtcm_test.py -n FIFB
python .\pyrtcm_test.py -n MIRO
python .\pyrtcm_test.py -n PTES
python .\pyrtcm_test.py -n BATY
python .\pyrtcm_test.py -n KUNP
python .\pyrtcm_test.py -n PYRUS
python .\pyrtcm_test.py -n MLGH
python .\pyrtcm_test.py -n RSZM
python .\pyrtcm_test.py -n KEBA
python .\pyrtcm_test.py -n TABI
python .\pyrtcm_test.py -n KLKD
python .\pyrtcm_test.py -n KOVA
python .\pyrtcm_test.py -n STGE
python .\pyrtcm_test.py -n VANDA
python .\pyrtcm_test.py -n SLVT
python .\pyrtcm_test.py -n AURAY
python .\pyrtcm_test.py -n BO12
python .\pyrtcm_test.py -n UP3F
python .\pyrtcm_test.py -n ASSAS
python .\pyrtcm_test.py -n EMONIE
python .\pyrtcm_test.py -n SRKA
python .\pyrtcm_test.py -n HAGY
python .\pyrtcm_test.py -n JOKI
python .\pyrtcm_test.py -n SGC
python .\pyrtcm_test.py -n MATO
python .\pyrtcm_test.py -n VAU
python .\pyrtcm_test.py -n TOOK
python .\pyrtcm_test.py -n MIELK
python .\pyrtcm_test.py -n KSZL
python .\pyrtcm_test.py -n AGDE
python .\pyrtcm_test.py -n RAJT
python .\pyrtcm_test.py -n SKY1
python .\pyrtcm_test.py -n GRASE
python .\pyrtcm_test.py -n MITTE
python .\pyrtcm_test.py -n ABA1
python .\pyrtcm_test.py -n HA49
python .\pyrtcm_test.py -n DANE
python .\pyrtcm_test.py -n DVSLO
python .\pyrtcm_test.py -n KLEG
python .\pyrtcm_test.py -n ZSG1
python .\pyrtcm_test.py -n GPEY
python .\pyrtcm_test.py -n BTRN
python .\pyrtcm_test.py -n TORS
python .\pyrtcm_test.py -n DELP
python .\pyrtcm_test.py -n LAJ39
python .\pyrtcm_test.py -n CASE
python .\pyrtcm_test.py -n ROQU
python .\pyrtcm_test.py -n PETI
python .\pyrtcm_test.py -n MERK
python .\pyrtcm_test.py -n MICH
python .\pyrtcm_test.py -n MOR02
python .\pyrtcm_test.py -n TOMI
python .\pyrtcm_test.py -n CMJB
python .\pyrtcm_test.py -n LMSN
python .\pyrtcm_test.py -n JRMI
python .\pyrtcm_test.py -n BEAUR
python .\pyrtcm_test.py -n VS17
python .\pyrtcm_test.py -n TOMA
python .\pyrtcm_test.py -n FUGE
python .\pyrtcm_test.py -n LOSI
python .\pyrtcm_test.py -n TESLA10
python .\pyrtcm_test.py -n MARINEL
python .\pyrtcm_test.py -n ZOKISEF
python .\pyrtcm_test.py -n NESA
python .\pyrtcm_test.py -n GUISS
python .\pyrtcm_test.py -n VRELY
python .\pyrtcm_test.py -n LANDE
python .\pyrtcm_test.py -n WAHB
python .\pyrtcm_test.py -n NONA
python .\pyrtcm_test.py -n DACH
python .\pyrtcm_test.py -n TOTH
python .\pyrtcm_test.py -n PCHSG1
python .\pyrtcm_test.py -n COLI
python .\pyrtcm_test.py -n SA35
python .\pyrtcm_test.py -n Knockclonagad
python .\pyrtcm_test.py -n JANC
python .\pyrtcm_test.py -n JDEV
python .\pyrtcm_test.py -n 5640
python .\pyrtcm_test.py -n NMSJ
python .\pyrtcm_test.py -n CHTL
python .\pyrtcm_test.py -n CBM1
python .\pyrtcm_test.py -n TUTU
python .\pyrtcm_test.py -n AUB1
python .\pyrtcm_test.py -n ROMS2
python .\pyrtcm_test.py -n DOUME
python .\pyrtcm_test.py -n DEPZ
python .\pyrtcm_test.py -n ENFP
python .\pyrtcm_test.py -n SMVD
python .\pyrtcm_test.py -n AMIEN
python .\pyrtcm_test.py -n OGAG
python .\pyrtcm_test.py -n GRAV
python .\pyrtcm_test.py -n MTVAL
python .\pyrtcm_test.py -n NLER
python .\pyrtcm_test.py -n mosskarr
python .\pyrtcm_test.py -n SURD
python .\pyrtcm_test.py -n SOSS
python .\pyrtcm_test.py -n CEREMA22
python .\pyrtcm_test.py -n CHBE
python .\pyrtcm_test.py -n FONCH
python .\pyrtcm_test.py -n PAND
python .\pyrtcm_test.py -n RICE
python .\pyrtcm_test.py -n BLIX
python .\pyrtcm_test.py -n CLAP
python .\pyrtcm_test.py -n MEGY
python .\pyrtcm_test.py -n FORG
python .\pyrtcm_test.py -n PV52
python .\pyrtcm_test.py -n TESTDECO
python .\pyrtcm_test.py -n TANYA
python .\pyrtcm_test.py -n KECS
python .\pyrtcm_test.py -n OLBO
python .\pyrtcm_test.py -n GRDO
python .\pyrtcm_test.py -n DURAS2
python .\pyrtcm_test.py -n DURAS
python .\pyrtcm_test.py -n HAF3
python .\pyrtcm_test.py -n HAGG
python .\pyrtcm_test.py -n TCY22
python .\pyrtcm_test.py -n CSK1
python .\pyrtcm_test.py -n SOMI
python .\pyrtcm_test.py -n MRTN
python .\pyrtcm_test.py -n GYUGY
python .\pyrtcm_test.py -n RKMZ
python .\pyrtcm_test.py -n OSZA
python .\pyrtcm_test.py -n SLKS
python .\pyrtcm_test.py -n ERD1
python .\pyrtcm_test.py -n LANONO
python .\pyrtcm_test.py -n ROCL1
python .\pyrtcm_test.py -n NPRT
python .\pyrtcm_test.py -n SOLA
python .\pyrtcm_test.py -n ZSNS
python .\pyrtcm_test.py -n TZTG
python .\pyrtcm_test.py -n HDTL
python .\pyrtcm_test.py -n BOKA
python .\pyrtcm_test.py -n TOT1
python .\pyrtcm_test.py -n OFFA
python .\pyrtcm_test.py -n COLOS
python .\pyrtcm_test.py -n OSZI
python .\pyrtcm_test.py -n BGNR
python .\pyrtcm_test.py -n ADNC
python .\pyrtcm_test.py -n MAGC
python .\pyrtcm_test.py -n ANSEB
python .\pyrtcm_test.py -n STME
python .\pyrtcm_test.py -n LORI
python .\pyrtcm_test.py -n MANI
python .\pyrtcm_test.py -n JAUB
python .\pyrtcm_test.py -n QE27
python .\pyrtcm_test.py -n DORI
python .\pyrtcm_test.py -n RSTL
python .\pyrtcm_test.py -n LGLR
python .\pyrtcm_test.py -n MOTI
python .\pyrtcm_test.py -n BABY
python .\pyrtcm_test.py -n ESIG
python .\pyrtcm_test.py -n CHARO
python .\pyrtcm_test.py -n AGBI
python .\pyrtcm_test.py -n NBMR
python .\pyrtcm_test.py -n CRO2
python .\pyrtcm_test.py -n FECO
python .\pyrtcm_test.py -n FECO1
python .\pyrtcm_test.py -n TUDJA
python .\pyrtcm_test.py -n ROYE
python .\pyrtcm_test.py -n NATT
python .\pyrtcm_test.py -n LEBE
python .\pyrtcm_test.py -n ALPE
python .\pyrtcm_test.py -n STOO
python .\pyrtcm_test.py -n BRET
python .\pyrtcm_test.py -n Filipgps
python .\pyrtcm_test.py -n MSBT
python .\pyrtcm_test.py -n VASZ
python .\pyrtcm_test.py -n LALI
python .\pyrtcm_test.py -n KUTI1
python .\pyrtcm_test.py -n PAPD
python .\pyrtcm_test.py -n ETOIL
python .\pyrtcm_test.py -n RAMA
python .\pyrtcm_test.py -n MENH
python .\pyrtcm_test.py -n TLB2
python .\pyrtcm_test.py -n KMLO
python .\pyrtcm_test.py -n TAMG
python .\pyrtcm_test.py -n FCMR
python .\pyrtcm_test.py -n KIKI
python .\pyrtcm_test.py -n SOE
python .\pyrtcm_test.py -n PRIME
python .\pyrtcm_test.py -n JE12
python .\pyrtcm_test.py -n CHA2
python .\pyrtcm_test.py -n AVR2
python .\pyrtcm_test.py -n ABAT
python .\pyrtcm_test.py -n LAB1
python .\pyrtcm_test.py -n PEPI
python .\pyrtcm_test.py -n KALM
python .\pyrtcm_test.py -n AKOS
python .\pyrtcm_test.py -n PAYS
python .\pyrtcm_test.py -n MORA
python .\pyrtcm_test.py -n CHARB
python .\pyrtcm_test.py -n FAB64
python .\pyrtcm_test.py -n GABAS
python .\pyrtcm_test.py -n LFD14
python .\pyrtcm_test.py -n ROSD
python .\pyrtcm_test.py -n RITZ
python .\pyrtcm_test.py -n MLKA
python .\pyrtcm_test.py -n HBC77
python .\pyrtcm_test.py -n PAU1
python .\pyrtcm_test.py -n SZCS
python .\pyrtcm_test.py -n BERN
python .\pyrtcm_test.py -n LORGI
python .\pyrtcm_test.py -n SFL1
python .\pyrtcm_test.py -n CHER
python .\pyrtcm_test.py -n DL72
python .\pyrtcm_test.py -n MNE1
python .\pyrtcm_test.py -n SMOD
python .\pyrtcm_test.py -n MATT
python .\pyrtcm_test.py -n TITI
python .\pyrtcm_test.py -n FR45
python .\pyrtcm_test.py -n AGRP
python .\pyrtcm_test.py -n MARS
python .\pyrtcm_test.py -n PLOE
python .\pyrtcm_test.py -n HARR
python .\pyrtcm_test.py -n FRNK
python .\pyrtcm_test.py -n BHNZ
python .\pyrtcm_test.py -n PROM
python .\pyrtcm_test.py -n PLQ1
python .\pyrtcm_test.py -n ARL72
python .\pyrtcm_test.py -n ABCD
python .\pyrtcm_test.py -n FILF
python .\pyrtcm_test.py -n NGD1
python .\pyrtcm_test.py -n COMBE
python .\pyrtcm_test.py -n LAUR
python .\pyrtcm_test.py -n BEFF
python .\pyrtcm_test.py -n BENG
python .\pyrtcm_test.py -n KARD
python .\pyrtcm_test.py -n MONTS
python .\pyrtcm_test.py -n RTKM
python .\pyrtcm_test.py -n HFRM
python .\pyrtcm_test.py -n GRBS
python .\pyrtcm_test.py -n GUNICS
python .\pyrtcm_test.py -n LH41
python .\pyrtcm_test.py -n WIWI
python .\pyrtcm_test.py -n AL89
python .\pyrtcm_test.py -n LTC1
python .\pyrtcm_test.py -n AMEL
python .\pyrtcm_test.py -n MEDH
python .\pyrtcm_test.py -n FAVE
python .\pyrtcm_test.py -n GABI
python .\pyrtcm_test.py -n KERL
python .\pyrtcm_test.py -n RDHB7
python .\pyrtcm_test.py -n RCZL
python .\pyrtcm_test.py -n SLP
python .\pyrtcm_test.py -n BAU5
python .\pyrtcm_test.py -n DETK
python .\pyrtcm_test.py -n HOUSY
python .\pyrtcm_test.py -n STURB1
python .\pyrtcm_test.py -n BELOS
python .\pyrtcm_test.py -n BAY40
python .\pyrtcm_test.py -n JANU
python .\pyrtcm_test.py -n GRMA
python .\pyrtcm_test.py -n CGRO
python .\pyrtcm_test.py -n JFDE
python .\pyrtcm_test.py -n JBCH
python .\pyrtcm_test.py -n INP01
python .\pyrtcm_test.py -n FRTK49